version: '3.7'
services:
  natcap:
    image: ternandsparrow/natcap-invest-docker-flask:${NATCAP_TAG:-deploy}
    build: ./
    container_name: natcap
    init: true
    environment:
      NIDF_ENV: ${NIDF_ENV:-development}
      SOCKETIO_SECRET: ${SOCKETIO_SECRET:-pssst}
      FARM_PADDING_METRES: 1500
      IS_CHOMP_FARM_VECTOR: 1
      SENTRY_DSN: ${SENTRY_DSN:-}
    restart: 'no'
    ports:
      - '${NATCAP_PORT:-5000}:5000'
    logging:
      driver: "json-file"
      options:
        max-size: 100m
